### ISSUE TITLE
Improve categorisation logic

### ISSUE THREAD

**Issue by ScaredIbis** [ScaredIbis/autochecker#4]
The method for categorising checkbox text could be improved. It currently just has big if conditions checking for certain words in the label text.

**Comment by Alaricus** [comment]
@JackAppDev, it seems great minds think alike. =) I just did exactly what you are suggesting in my pull request. Although I didn't see your suggestion until after I submitted it, I feel you deserve the credit for being the first!

**Comment by chrdevmar** [comment]
Thanks for the suggestion @JackAppDev, much appreciated.

And thanks @Alaricus for implementing.
